### ISSUE TITLE
Adding items to free slots

### ISSUE THREAD

**Issue by GalaxyDevourer** [cervinakuy/JoinEventsPro#1]
Hello
I ran into the problem of overwriting the current item in inventory with a item from the plugin. This is not very good, for example, so the player may lose a enchanted sword or a stack of diamonds ...

It would be nice to add the ability to move an item (current or issued by the plugin) into an empty slot, and if all the slots are occupied, give a warning message.

I think this is not so difficult to do, but it will be very useful (I would say it is necessary)
Best wishes in development :)

**Comment by cervinakuy** [comment]
Thanks, this will be included in the next update.
